# Generated by Django 4.1.2 on 2022-10-28 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=35)),
                ('id_num', models.IntegerField()),
                ('adress', models.CharField(max_length=50)),
                ('pet_name', models.CharField(max_length=35)),
            ],
        ),
    ]
