# Generated by Django 4.1.2 on 2022-10-29 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='owner',
            old_name='full_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='owner',
            old_name='id_num',
            new_name='phone',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='pet_name',
        ),
    ]
