# Generated by Django 4.1.2 on 2022-10-28 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal', models.CharField(max_length=35)),
                ('breed', models.CharField(max_length=35)),
                ('name', models.CharField(max_length=35)),
                ('age', models.IntegerField()),
            ],
        ),
    ]
